# Generated by Django 3.1.7 on 2021-03-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='FirstName')),
                ('last_name', models.CharField(max_length=50, verbose_name='LastName')),
                ('email', models.EmailField(max_length=254)),
                ('spotify_customer', models.BooleanField(default=False)),
                ('google_music_customer', models.BooleanField(default=False)),
                ('pandora_customer', models.BooleanField(default=False)),
                ('other_customer', models.BooleanField(default=False)),
            ],
        ),
    ]
