# Generated by Django 3.1.7 on 2021-03-10 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
    ]
