# Generated by Django 3.1.7 on 2021-03-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='other_customer',
            field=models.BooleanField(default=False),
        ),
    ]
